prompt creating audit table and DDL trigger (DEV-only recommended)

create table oei_env_sync_audit (
    audit_id        number generated by default on null as identity primary key,
    event_time      timestamp       default systimestamp not null,
    login_user      varchar2(128)   not null,
    os_user         varchar2(128),
    ip_address      varchar2(64),
    machine         varchar2(128),
    module          varchar2(128),
    terminal        varchar2(128),
    event           varchar2(30)    not null,
    object_owner    varchar2(128),
    object_name     varchar2(128),
    object_type     varchar2(30),
    ddl_text        clob
);

comment on table oei_env_sync_audit is 'Captures DDL activity in schema for traceability (recommended for DEV only).';

create or replace trigger oei_env_sync_audit_trg
after ddl on schema
declare
    l_sql_list  ora_name_list_t;
    l_stmt      clob;
    l_n         pls_integer;
begin
    -- Assemble full statement text
    l_n := ora_sql_txt(l_sql_list);
    if l_n > 0 then
        for i in 1 .. l_n loop
            l_stmt := l_stmt || l_sql_list(i);
        end loop;
    end if;

    insert into oei_env_sync_audit (
        event_time,
        login_user,
        os_user,
        ip_address,
        machine,
        module,
        terminal,
        event,
        object_owner,
        object_name,
        object_type,
        ddl_text)
    values (
        systimestamp,
        sys_context('USERENV','SESSION_USER'),
        sys_context('USERENV','OS_USER'),
        sys_context('USERENV','IP_ADDRESS'),
        sys_context('USERENV','HOST'),
        sys_context('USERENV','MODULE'),
        sys_context('USERENV','TERMINAL'),
        ora_sysevent,
        ora_dict_obj_owner,
        ora_dict_obj_name,
        ora_dict_obj_type,
        l_stmt);
end;
/

-- Helpers to enable/disable audit quickly
create or replace procedure oei_env_sync_audit_enable as
begin
    execute immediate 'alter trigger oei_env_sync_audit_trg enable';
end;
/

create or replace procedure oei_env_sync_audit_disable as
begin
    execute immediate 'alter trigger oei_env_sync_audit_trg disable';
end;
/

