prompt creating table oei_env_sync_releases ...

create table oei_env_sync_releases (
    release_id     number generated by default on null as identity primary key,
    status         varchar2(20)    not null,
    release_title  varchar2(200),
    manifest_json  clob            not null,
    script_clob    clob            not null,
    script_hash    varchar2(64)    not null,
    created_by     varchar2(128)   default sys_context('USERENV','SESSION_USER') not null,
    created_on     timestamp       default systimestamp not null,
    approved_by    varchar2(128),
    approved_on    timestamp,
    constraint ck_env_sync_release_status check (status in ('DRAFT','APPROVED','RELEASED'))
);

comment on table oei_env_sync_releases is 'Release bundles containing manifest (JSON list of changes) and generated install script with hash.';
comment on column oei_env_sync_releases.script_hash is 'SHA-256 hash (hex lowercase) of script_clob content.';

