prompt creating table oei_env_sync_schema_objects ...
create table oei_env_sync_schema_objects (
    id              number generated by default on null as identity primary key,
    schema_name     varchar2(128) not null,
    object_type     varchar2(30)  not null,
    object_name     varchar2(128) not null,
    captured_on     timestamp default systimestamp not null,
    payload         clob not null,
    ddl_hash        varchar2(64), -- SHA-256 hex of normalized DDL (when available)
    constraint oei_env_sync_schema_objects_uq unique (schema_name, object_type, object_name)
);

-- ensure that the payload column is created and has a segment assigned
-- this block intentionally ignores missing LOB metadata (for example before
-- the table is created) so that the script can be executed idempotently.
declare
    l_segname user_lobs.segment_name%type;
begin
    select segment_name
      into l_segname
      from user_lobs
     where table_name = upper('oei_env_sync_schema_objects')
       and column_name = upper('payload');
exception
    when no_data_found then
        null;
end;
/
