prompt creating table oei_env_sync_install_log ...

create table oei_env_sync_install_log (
    install_id     number generated by default on null as identity primary key,
    release_id     number          not null,
    target_schema  varchar2(128)   not null,
    installed_by   varchar2(128)   default sys_context('USERENV','SESSION_USER') not null,
    installed_on   timestamp       default systimestamp not null,
    success        char(1)         check (success in ('Y','N')),
    log_clob       clob,
    constraint fk_install_log_release foreign key (release_id)
        references oei_env_sync_releases (release_id) on delete cascade
);

comment on table oei_env_sync_install_log is 'Audit of releases installed into target schemas with outcome and optional log.';

