prompt creating table oei_env_sync_snapshots ...

create table oei_env_sync_snapshots (
    snapshot_id    number generated by default on null as identity primary key,
    snapshot_name  varchar2(200) not null,
    target_schema  varchar2(128),
    source_env     varchar2(200),
    payload        clob           not null,
    created_by     varchar2(128)  default sys_context('USERENV','SESSION_USER') not null,
    created_on     timestamp      default systimestamp not null
);

comment on table oei_env_sync_snapshots is 'Stores uploaded object lists (JSON) representing target environment snapshots.';
comment on column oei_env_sync_snapshots.payload is 'JSON array of objects with at least object_type and object_name; schema_name optional.';

