PROMPT Creating table INSTALL_SCRIPT_STRATEGY;

CREATE TABLE install_script_strategy (
    strategy_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    strategy_name          VARCHAR2(100)    NOT NULL,
    generation_mode        VARCHAR2(20)     NOT NULL,
    custom_script          CLOB,
    created_at             DATE             DEFAULT SYSDATE NOT NULL,
    updated_at             DATE,
    CONSTRAINT pk_install_script_strategy PRIMARY KEY (strategy_id),
    CONSTRAINT uq_install_script_strategy_name UNIQUE (strategy_name),
    CONSTRAINT ck_install_script_strategy_mode CHECK (generation_mode IN ('DDL', 'CUSTOM')),
    CONSTRAINT ck_install_script_strategy_custom CHECK (
        (generation_mode = 'DDL'   AND custom_script IS NULL)
        OR
        (generation_mode = 'CUSTOM' AND custom_script IS NOT NULL)
    )
);

COMMENT ON TABLE install_script_strategy IS 'Configura a forma de gerar os scripts de instalacao (DDL automatica ou script customizado).';
COMMENT ON COLUMN install_script_strategy.generation_mode IS 'DDL ou CUSTOM, indicando se o script sera gerado a partir dos DDLs ou de um script fornecido.';
COMMENT ON COLUMN install_script_strategy.custom_script IS 'Conteudo do script customizado quando generation_mode = CUSTOM.';

PROMPT Creating table INSTALL_SCRIPT_STRATEGY_NAMING;

CREATE TABLE install_script_strategy_naming (
    naming_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    strategy_id     NUMBER          NOT NULL,
    object_type     VARCHAR2(30)    NOT NULL,
    name_prefix     VARCHAR2(50),
    name_suffix     VARCHAR2(50),
    CONSTRAINT pk_install_script_strategy_naming PRIMARY KEY (naming_id),
    CONSTRAINT uq_install_script_strategy_naming UNIQUE (strategy_id, object_type),
    CONSTRAINT fk_install_strategy_naming_strategy FOREIGN KEY (strategy_id)
        REFERENCES install_script_strategy (strategy_id)
        ON DELETE CASCADE
);

COMMENT ON TABLE install_script_strategy_naming IS 'Define prefixos e sufixos por tipo de objecto para estrategias CUSTOM.';
COMMENT ON COLUMN install_script_strategy_naming.object_type IS 'Tipo de objecto Oracle (por exemplo TABLE, SEQUENCE, VIEW).';
COMMENT ON COLUMN install_script_strategy_naming.name_prefix IS 'Prefixo opcional aplicado aos objectos do tipo indicado.';
COMMENT ON COLUMN install_script_strategy_naming.name_suffix IS 'Sufixo opcional aplicado aos objectos do tipo indicado.';

CREATE OR REPLACE TRIGGER trg_install_script_strategy_audit
    BEFORE INSERT OR UPDATE ON install_script_strategy
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.created_at := NVL(:NEW.created_at, SYSDATE);
    END IF;
    :NEW.updated_at := SYSDATE;
END;
/

