PROMPT Creating table INSTALL_SCRIPT_STRATEGY;

CREATE TABLE install_script_strategy (
    strategy_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    strategy_name          VARCHAR2(100)    NOT NULL,
    generation_mode        VARCHAR2(20)     NOT NULL,
    custom_script          CLOB,
    object_name_prefix     VARCHAR2(50),
    object_name_suffix     VARCHAR2(50),
    created_at             DATE             DEFAULT SYSDATE NOT NULL,
    updated_at             DATE,
    CONSTRAINT pk_install_script_strategy PRIMARY KEY (strategy_id),
    CONSTRAINT uq_install_script_strategy_name UNIQUE (strategy_name),
    CONSTRAINT ck_install_script_strategy_mode CHECK (generation_mode IN ('DDL', 'CUSTOM')),
    CONSTRAINT ck_install_script_strategy_custom CHECK (
        (generation_mode = 'DDL'   AND custom_script IS NULL)
        OR
        (generation_mode = 'CUSTOM' AND custom_script IS NOT NULL)
    )
);

COMMENT ON TABLE install_script_strategy IS 'Configura a forma de gerar os scripts de instalacao (DDL automatica ou script customizado).';
COMMENT ON COLUMN install_script_strategy.generation_mode IS 'DDL ou CUSTOM, indicando se o script sera gerado a partir dos DDLs ou de um script fornecido.';
COMMENT ON COLUMN install_script_strategy.custom_script IS 'Conteudo do script customizado quando generation_mode = CUSTOM.';
COMMENT ON COLUMN install_script_strategy.object_name_prefix IS 'Prefixo opcional aplicado aos nomes de objectos quando generation_mode = CUSTOM.';
COMMENT ON COLUMN install_script_strategy.object_name_suffix IS 'Sufixo opcional aplicado aos nomes de objectos quando generation_mode = CUSTOM.';

CREATE OR REPLACE TRIGGER trg_install_script_strategy_audit
    BEFORE INSERT OR UPDATE ON install_script_strategy
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.created_at := NVL(:NEW.created_at, SYSDATE);
    END IF;
    :NEW.updated_at := SYSDATE;
END;
/

