prompt creating table oei_install_script_strategy;

create table oei_install_script_strategy (
    strategy_id            number generated by default as identity,
    strategy_name          varchar2(100)    not null,
    generation_mode        varchar2(20)     not null,
    custom_script          clob,
    created_at             date             default sysdate not null,
    updated_at             date,
    constraint pk_install_script_strategy primary key (strategy_id),
    constraint uq_install_script_strategy_name unique (strategy_name),
    constraint ck_install_script_strategy_mode check (generation_mode in ('DDL', 'CUSTOM')),
    constraint ck_install_script_strategy_custom check (
        (generation_mode = 'DDL'   and custom_script is null)
        or
        (generation_mode = 'CUSTOM' and custom_script is not null)
    )
);

comment on table oei_install_script_strategy is 'Configura a forma de gerar os scripts de instalacao (DDL automatica ou script customizado).';
comment on column oei_install_script_strategy.generation_mode is 'DDL ou CUSTOM, indicando se o script sera gerado a partir dos DDLs ou de um script fornecido.';
comment on column oei_install_script_strategy.custom_script is 'Conteudo do script customizado quando generation_mode = CUSTOM.';

prompt creating table oei_install_script_strategy_naming;

create table oei_install_script_strategy_naming (
    naming_id       number generated by default as identity,
    strategy_id     number          not null,
    object_type     varchar2(30)    not null,
    name_prefix     varchar2(50),
    name_suffix     varchar2(50),
    constraint pk_install_script_strategy_naming primary key (naming_id),
    constraint uq_install_script_strategy_naming unique (strategy_id, object_type),
    constraint fk_install_strategy_naming_strategy foreign key (strategy_id)
        references oei_install_script_strategy (strategy_id)
        on delete cascade
);

comment on table oei_install_script_strategy_naming is 'Define prefixos e sufixos por tipo de objecto para estrategias CUSTOM.';
comment on column oei_install_script_strategy_naming.object_type is 'Tipo de objecto Oracle (por exemplo TABLE, SEQUENCE, VIEW).';
comment on column oei_install_script_strategy_naming.name_prefix is 'Prefixo opcional aplicado aos objectos do tipo indicado.';
comment on column oei_install_script_strategy_naming.name_suffix is 'Sufixo opcional aplicado aos objectos do tipo indicado.';

create or replace trigger trg_install_script_strategy_audit
    before insert or update on oei_install_script_strategy
    for each row
begin
    if inserting then
        :new.created_at := nvl(:new.created_at, sysdate);
    end if;
    :new.updated_at := sysdate;
end;
/

